name: Build

on:
    push:
        branches: [master, CI]
        tags: v*
    pull_request:
        branches: [master]

jobs:
    Build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v2
            - name: Setup Nuget
              uses: Nuget/setup-nuget@v1.0.5

            - name: Restore nuget packages
              run: nuget restore ${{ github.workspace }}/VoiceCommander.sln
            - name: Initialize modding environment
              uses: beat-forge/init-beatsaber@v1.1.0
              with:
                  token: ${{ github.token }}
                  version: 1.29.0
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{ github.workspace }}/VoiceCommander/manifest.json
            - name: Build
              id: Build
              run: msbuild ${{ github.workspace }}/VoiceCommander.sln /property:Configuration=Release
            - name: GitStatus
              run: git status
            - name: Read variables from file and set outputs
              id: set-outputs
              run: |
                while IFS=';' read -ra vars; do
                  for var in "${vars[@]}"; do
                    IFS='=' read -r key value <<< "$var"
                    echo "$key=$value" >> $GITHUB_OUTPUT
                  done
                done < build_output.txt
            - name: Echo Filename
              run: echo $BUILDTEXT $ASSEMBLYNAME
              env:
                  BUILDTEXT: Filename=${{ steps.set-outputs.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.set-outputs.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.set-outputs.outputs.filename }}.zip
                  path: ${{ steps.set-outputs.outputs.artifactpath }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ${{ steps.set-outputs.outputs.filename }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}